### ISSUE TITLE
"Schema must be an instance of GraphQLSchema"

### ISSUE THREAD

**Issue by advance512** [yarax/swagger-to-graphql#12]
When running the example with the following package.json:

```
{
  "name": "swagger-to-graphql-test",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "express": "^4.15.2",
    "express-graphql": "^0.6.3",
    "graphql": "^0.9.1",
    "swagger-to-graphql": "^1.0.4"
  }
}
```

I get the following in /graphql:

```
{
  "errors": [
    {
      "message": "Schema must be an instance of GraphQLSchema. Also ensure that there are not multiple versions of GraphQL installed in your node_modules directory."
    }
  ]
}
```

**Comment by mattiaerre** [comment]
@advance512 it looks like that `"graphql": "^0.8.2"` works while `"graphql": "^0.9.1"` doesn't; try to downgrade and see what you've got. I will try to have a look at the source code and see if I can find the root cause of this bug.

**Comment by yarax** [comment]
Hi!
Thanks for the issue. This error looks more like problem with schema.
I've tried your package.json and it works well with petstore schema.

**Comment by advance512** [comment]
I use my schema in Bravado, Connexion and other swagger-codegen. I doubt it is an issue with it..

**Comment by yarax** [comment]
No, I mean Swagger schema could be completely correct, but its structure can initiate wrapper error. Can you provide your schema for debugging?

**Comment by kirill-konshin** [comment]
Got the same error with the spec from `test/fixtures/petstore.json`.

**Comment by kirill-konshin** [comment]
The problem is that even with deps like mentioned above the package `swagger-to-graphql` has its own version of `graphql` in nested `node_modules` dir. Pls update your `package.json` to have `graphql` as `peerDependency` and not as `dependency`.

**Comment by yarax** [comment]
You are right, thanks, will publish a new version to npm soon

**Comment by LGLC** [comment]
@yarax Is there a version that's been pushed to npm with the `peerDependency` instead of a `dependency`?  I'm still getting the same error as above.  

If I try the suggestion by @kirill-konshin of removing the `graphql` dependency in my main project, I get errors as `express-graphql` complains the module isn't installed (as it's a `peerDependency` of it).  Yet if I leave it in, then `swagger-to-graphql` is also installing a version of it, meaning I have two version installed and get the original error.

I think the example app inside `swagger-to-graphql` happens to work as it actually *is* the library, so therefore there's no conflict in folders (i.e. the example installs `graphql` to `./node_modules`, and `swagger-to-graphql` also installs it to the exact same folder, so there aren't two versions).

**Comment by LGLC** [comment]
Actually, deleting `node_modules` first, then `removing the `graphql` dependency and running `npm install` has worked.  It must have been my other version of `graphql` that remained there.  Making it a `peerDependency` would still be nice though if possible.  Thanks!
