### ISSUE TITLE
Customize default resolver

### ISSUE THREAD

**Issue by thealjey** [yarax/swagger-to-graphql#158]
Is it possible to customize the default resolver to perform additional manipulation in the data returned from a Rest API?

**Comment by 0xR** [comment]
Yes, since version 3 you provide your own data fetching callback called `callBackend`. You can perform postprocessing after your fetch the data.

Note your response still needs to conform to the schema that is provided by your swagger schema.

If you want to make customizations that also change the response schema you could have a look at [schema transforms](https://www.apollographql.com/docs/graphql-tools/schema-transforms/).

If you are looking to do transformation where you join across different Rest endpoints you could use [schema stitching](https://www.apollographql.com/docs/graphql-tools/schema-stitching/). Note the docs mention it is deprecated, this is because it is replaced by federation. However, for making joins within your own schema I recommend it over federation.

**Comment by thealjey** [comment]
thank you!
